name: Release

on:
  push:
    branches:
      - 'enableLater'
    tags-ignore:
      - '**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: Install dependencies
      run: |
        npm install
        apt install unbuffer
    - name: Install CLI
      run: |
        npm install -g
    - name: test
      run: |
        npm run test
    - name: Release
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
